import typing

MINECRAFT_NAMESPACE_PREFIX: typing.Final[str] = "minecraft:"

GENERATED_MCFUNCTION_PREFIX: typing.Final[
    str
] = "# THIS FILE IS GENERATED BY MCDIC'S PYTHON SCRIPT"

DEFAULT_BLOCK_MODIFICATION_LIMIT: typing.Final[int] = 65536

AVAILABLE_BLOCK_COLORS = typing.Literal[
    "white",
    "light_gray",
    "gray",
    "black",
    "brown",
    "red",
    "orange",
    "yellow",
    "lime",
    "green",
    "cyan",
    "light_blue",
    "blue",
    "purple",
    "magenta",
    "pink",
]

LEFT_END: typing.Final[int] = -64
RIGHT_END: typing.Final[int] = 63
